#!/bin/sh

if [ "$#" -ne 3 ]; then
    echo "Decrypt SQLite database."
    echo "Usage: sqldec <encrypted-db> <plain-db> <key>"
    exit 1
fi

ENCRYPTED_DB=$1
PLAIN_DB=$2
ENCRYPTION_KEY=$3

if test ! -f "$ENCRYPTED_DB"; then
    echo "File $ENCRYPTED_DB does not exist"
    exit 1
fi

if test -f "$PLAIN_DB"; then
    echo "File $PLAIN_DB already exists"
    exit 1
fi

SCRIPT="PRAGMA key = '${ENCRYPTION_KEY}';"
SCRIPT+="ATTACH DATABASE '${PLAIN_DB}' AS decrypted KEY '';"
SCRIPT+="SELECT sqlcipher_export('decrypted');"
SCRIPT+="DETACH DATABASE decrypted;"

echo $SCRIPT | sqlcipher $ENCRYPTED_DB